# Generated by Django 3.1.2 on 2021-01-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=45)),
                ('e_mail', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=45)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
            ],
            options={
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('metodo', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('datentrega', models.CharField(max_length=8)),
                ('datpedido', models.CharField(blank=True, max_length=8, null=True)),
                ('valorTotal', models.DecimalField(decimal_places=6, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('id_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pagamento')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('tipo_solicitacao', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status')),
                ('id_tipoSolicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiposolicitacao')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('titulo', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('escala', models.CharField(max_length=45)),
                ('lote', models.DecimalField(decimal_places=6, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=6, max_digits=10)),
                ('unidades_vendidas', models.DecimalField(decimal_places=6, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_veiculos')),
                ('id_fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fabricante')),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia_pedido', models.DecimalField(decimal_places=6, max_digits=10)),
                ('quantidade_itens', models.DecimalField(decimal_places=6, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=6, max_digits=10)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'verbose_name_plural': 'Itens Pedidos',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor'),
        ),
        migrations.CreateModel(
            name='Carrrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'verbose_name_plural': 'Carrinhos',
            },
        ),
    ]
