# Generated by Django 3.1.5 on 2021-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210111_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='e_mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_produtos'),
        ),
    ]
