# Generated by Django 3.1.2 on 2021-01-14 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210114_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='id_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status'),
        ),
    ]
